//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSU_Launcher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MSU")]
        public string MSUPathSetting {
            get {
                return ((string)(this["MSUPathSetting"]));
            }
            set {
                this["MSUPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\BerserkerMultiWorld\\QUsb2Snes\\QUsb2Snes.exe")]
        public string QUsb2SnesPathSetting {
            get {
                return ((string)(this["QUsb2SnesPathSetting"]));
            }
            set {
                this["QUsb2SnesPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\livesplit\\rando.lsl")]
        public string LiveSplitPathSetting {
            get {
                return ((string)(this["LiveSplitPathSetting"]));
            }
            set {
                this["LiveSplitPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LiveSplitEnabledSetting {
            get {
                return ((bool)(this["LiveSplitEnabledSetting"]));
            }
            set {
                this["LiveSplitEnabledSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\EmoTracker\\EmoTracker.exe")]
        public string EmoTrackerPathSetting {
            get {
                return ((string)(this["EmoTrackerPathSetting"]));
            }
            set {
                this["EmoTrackerPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmoTrackerEnabledSetting {
            get {
                return ((bool)(this["EmoTrackerEnabledSetting"]));
            }
            set {
                this["EmoTrackerEnabledSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%userprofile%\\downloads")]
        public string DownloadsPathSetting {
            get {
                return ((string)(this["DownloadsPathSetting"]));
            }
            set {
                this["DownloadsPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteSetting {
            get {
                return ((bool)(this["OverwriteSetting"]));
            }
            set {
                this["OverwriteSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomMSUSetting {
            get {
                return ((bool)(this["RandomMSUSetting"]));
            }
            set {
                this["RandomMSUSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QUsb2SnesEnabledSetting {
            get {
                return ((bool)(this["QUsb2SnesEnabledSetting"]));
            }
            set {
                this["QUsb2SnesEnabledSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("615")]
        public int SizeXSetting {
            get {
                return ((int)(this["SizeXSetting"]));
            }
            set {
                this["SizeXSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int SizeYSetting {
            get {
                return ((int)(this["SizeYSetting"]));
            }
            set {
                this["SizeYSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SplitDistanceSetting {
            get {
                return ((int)(this["SplitDistanceSetting"]));
            }
            set {
                this["SplitDistanceSetting"] = value;
            }
        }
    }
}
