//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSU_Launcher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MSU")]
        public string MSUPathSetting {
            get {
                return ((string)(this["MSUPathSetting"]));
            }
            set {
                this["MSUPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Brian\\Documents\\SNES\\EMULATOR\\snes9x.exe")]
        public string SNES9xPathSetting {
            get {
                return ((string)(this["SNES9xPathSetting"]));
            }
            set {
                this["SNES9xPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Brian\\Desktop\\livesplit\\rando.lsl")]
        public string LiveSplitPathSetting {
            get {
                return ((string)(this["LiveSplitPathSetting"]));
            }
            set {
                this["LiveSplitPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LiveSplitEnabled {
            get {
                return ((bool)(this["LiveSplitEnabled"]));
            }
            set {
                this["LiveSplitEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\EmoTracker\\EmoTracker.exe")]
        public string EmoTrackerPathSetting {
            get {
                return ((string)(this["EmoTrackerPathSetting"]));
            }
            set {
                this["EmoTrackerPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmoTrackerEnabled {
            get {
                return ((bool)(this["EmoTrackerEnabled"]));
            }
            set {
                this["EmoTrackerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%userprofile%\\downloads")]
        public string DownloadsPathSetting {
            get {
                return ((string)(this["DownloadsPathSetting"]));
            }
            set {
                this["DownloadsPathSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteSetting {
            get {
                return ((bool)(this["OverwriteSetting"]));
            }
            set {
                this["OverwriteSetting"] = value;
            }
        }
    }
}
